apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: stephengrider/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: stephengrider/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
deploy:
  kubectl:
    manifests:
      - "k8s/client-deployment.yaml"
      - "k8s/server-deployment.yaml"
      - "k8s/server-cluster-ip-service.yaml"
      - "k8s/client-cluster-ip-service.yaml"
